# Generated by Django 2.2.11 on 2020-03-31 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
